using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid.Views.Grid.ViewInfo;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ASMAADEVEXPRESS.FRM
{
    public partial class test : DevExpress.XtraEditors.XtraForm
    {
        public test()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            
            gridView1.MasterRowExpanded += GridView1_MasterRowExpanded;
        }

        private void GridView1_MasterRowExpanded(object sender, CustomMasterRowEventArgs e)
        {
            GridView master = sender as GridView;
            GridView detail = master.GetDetailView(e.RowHandle, e.RelationIndex) as GridView;
            detail.Click += Detail_Click;
        }

        private void Detail_Click(object sender, EventArgs e)
        {
            GridView gridView = sender as GridView;
         //   var value = gridView.GetSelectedRows();
            var value = gridView.GetRowCellValue(gridView.FocusedRowHandle, gridView.FocusedColumn);
            MessageBox.Show("Cell value: " + value.ToString(), "Message");
        }

      

        private void test_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'contract_invoiceDataSet.project_table' table. You can move, or remove it, as needed.
        }
    }
}